/**
 * Convention-based asset discovery. Dropping a correctly-named file into
 * src/assets/ink is the entire handover: no import to add, no registry to edit.
 *
 * This also means partial delivery works — two character poses can ship while
 * the other four are still placeholders, and nothing breaks or waits. That is
 * why the filenames in the asset brief are exact rather than suggestions.
 *
 * Assets live under src/ rather than public/ so Vite fingerprints, hashes and
 * code-splits them; public/ files are copied raw with no cache-busting.
 */

const found = import.meta.glob('./ink/**/*.{png,webp,svg}', {
  eager: true,
  query: '?url',
  import: 'default',
}) as Record<string, string>

function pick(folder: string, name: string): string | undefined {
  const key = Object.keys(found).find((path) => path.includes(`/${folder}/${name}.`))
  return key ? found[key] : undefined
}

function collect(folder: string): string[] {
  return Object.keys(found)
    .filter((path) => path.includes(`/${folder}/`))
    .sort()
    .map((path) => found[path])
}

export type Pose = 'idle' | 'walk' | 'point' | 'guard' | 'sit' | 'guitar'

export const POSES: Pose[] = ['idle', 'walk', 'point', 'guard', 'sit', 'guitar']

export const assets = {
  /** Hand-drawn cutouts of Durva. Undefined until the drawings land. */
  character: Object.fromEntries(
    POSES.map((pose) => [pose, pick('character', `durva-${pose}`)]),
  ) as Record<Pose, string | undefined>,

  /** Generated by the p5.brush mark factory — these exist today. */
  marks: {
    splats: collect('marks').filter((url) => url.includes('splat')),
    strokes: collect('marks').filter((url) => url.includes('stroke')),
    hatches: collect('marks').filter((url) => url.includes('hatch')),
    blot: pick('marks', 'blot-01'),
  },

  /** Handwritten margin notes, keyed by slug. */
  note: (slug: string) => pick('notes', `note-${slug}`),

  /** The carved seal. Falls back to the CSS circle until scanned. */
  hanko: pick('', 'hanko'),
} as const

export function hasCharacter(pose: Pose): boolean {
  return Boolean(assets.character[pose])
}
